addressbook/urls.py
# from django.conf.urls import patterns, url
from django.conf.urls import url
from django.urls import path, include
from . import views

# urlpatterns = patterns('addressbook.views',
#     url(r'^$', 'index', name='addressbook_index'),
#
#     url(r'^group/add$', 'add_group', name='addressbook_add_group'),
#
#     url(r'^contact/add$', 'add_contact', name='addressbook_add_contact'),
#     url(r'^contact/(?P<pk>\d+)/edit$', 'edit_contact',
#             name='addressbook_edit_contact'),
#     url(r'^contact/(?P<pk>\d+)/view$', 'single_contact',
#             name='addressbook_single_contact'),
#     url(r'^contact/(?P<pk>\d+)/download$', 'download_vcard',
#             name='addressbook_download_vcard'),
# )

# urlpatterns = [
#     path(addressbook.views),
#     url(r'^$', 'index', name='addressbook_index'),
#
#     url(r'^group/add$', 'add_group', name='addressbook_add_group'),
#
#     url(r'^contact/add$', 'add_contact', name='addressbook_add_contact'),
#     url(r'^contact/(?P<pk>\d+)/edit$', 'edit_contact',
#             name='addressbook_edit_contact'),
#     url(r'^contact/(?P<pk>\d+)/view$', 'single_contact',
#             name='addressbook_single_contact'),
#     url(r'^contact/(?P<pk>\d+)/download$', 'download_vcard',
#             name='addressbook_download_vcard'),
# ]

app_name = 'addressbook'

urlpatterns = [
    path('index/', views.index, name='addressbook_index'),

    path('add_group/', views.add_group, name='addressbook_add_group'),

    path('add_contact/', views.add_contact, name='addressbook_add_contact'),
    path('edit_contact/', views.edit_contact, name='addressbook_edit_contact'),
    path('<int:pk>/view', views.single_contact, name='addressbook_single_contact'),
    path('<int:pk>/download', views.download_vcard, 'download_vcard', name='addressbook_download_vcard'),
]

addressbook_tester/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('addressbook/', include('addressbook.urls'))
    #url(r'^addressbook/', include('addressbook.urls')),
]

addressbook/forms.py
from django.forms import ModelForm
from django_localflavor_us.forms import USZipCodeField
from django.forms.formsets import BaseFormSet, formset_factory
from django.forms.models import inlineformset_factory, BaseInlineFormSet 
from django.forms import ValidationError

from addressbook.models import *

class RequiredFormSet(BaseFormSet):
    def __init__(self, *args, **kwargs):
        super(RequiredFormSet, self).__init__(*args, **kwargs)
        for form in self.forms:
            form.empty_permitted = False

class ContactGroupForm(ModelForm):
    class Meta:
        model = ContactGroup
        fields = ('name',)

class ContactForm(ModelForm):
    def __init__(self, *pa, **ka):
        user = ka.pop('user')
        super(ContactForm, self).__init__(*pa, **ka)
        self.fields['group'].queryset = ContactGroup.objects.filter(user=user)

    class Meta:
        model = Contact
        fields = ('last_name',)  #TODO: OH Kanskje feil?

class SocialNetworkForm(ModelForm):
    class Meta:
        model = SocialNetwork
        fields = ('handle', 'type', 'public_visible', 'contact_visible')

class WebsiteForm(ModelForm):
    class Meta:
        model = Website
        fields = ('website', 'type', 'public_visible', 'contact_visible')

class EmailForm(ModelForm):
    class Meta:
        model = Email
        fields = ('email', 'type', 'public_visible', 'contact_visible')

class PhoneForm(ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ('phone', 'type', 'public_visible', 'contact_visible')

class AddressForm(ModelForm):
    zip = USZipCodeField
    
    class Meta:
        model = Address
        fields = ('street','city','state','zip', 'type', 'public_visible', 'contact_visible')


class MandatoryInlineFormSet(BaseInlineFormSet):
    def is_valid(self):
        return super(MandatoryInlineFormSet, self).is_valid() and \
                    not any([bool(e) for e in self.errors])  

    def clean(self):
        count = 0
        for form in self.forms:
            try:
                if form.cleaned_data and not form.cleaned_data.get('DELETE', False):
                    count += 1
            except AttributeError:
                # annoyingly, if a subform is invalid Django explicity raises
                # an AttributeError for cleaned_data
                pass
        if count < 1:
            raise ValidationError('You must have at least one of these.')

PhoneFormSet = formset_factory(PhoneForm, max_num=3, formset=RequiredFormSet)
AddressFormSet = formset_factory(AddressForm, max_num=3, formset=RequiredFormSet)
EmailFormSet = formset_factory(EmailForm, max_num=3, formset=RequiredFormSet)
WebsiteFormSet = formset_factory(WebsiteForm, max_num=3, formset=RequiredFormSet)
SocialNetworkFormSet = formset_factory(SocialNetworkForm, max_num=3, formset=RequiredFormSet)

ContactFormSet = inlineformset_factory(ContactGroup, Contact, max_num=4, extra=1, can_delete=False, fields=('last_name',))
EmailEditFormSet = inlineformset_factory(Contact, Email, extra=1, formset=MandatoryInlineFormSet, fields=('email',))
PhoneEditFormSet = inlineformset_factory(Contact, PhoneNumber, extra=1, can_delete=True, fields=('phone',))
AddressEditFormSet = inlineformset_factory(Contact, Address, extra=1, formset=MandatoryInlineFormSet, fields=('street',))
WebsiteEditFormSet = inlineformset_factory(Contact, Website, extra=1, can_delete=True, fields=('website',))
SocialNetworkEditFormSet = inlineformset_factory(Contact, SocialNetwork, extra=1, can_delete=True, fields=('handle',))

addressbook/views.py
import hashlib

from django.contrib.auth.decorators import login_required
# from django.core.urlresolvers import reverse
from django.urls.base import reverse
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import render
from django.template.context import RequestContext

from addressbook.forms import *
from addressbook.models import *
#from helper import VCard
from vobject import vCard as VCard

from django.http import HttpResponse
from django.template import loader

from django.views import generic


@login_required
def add_group(request):
    if request.method == "GET":
        form = ContactGroupForm()
    else:
        group = ContactGroup(user=request.user)
        form = ContactGroupForm(request.POST, instance=group)
        if form.is_valid():
            form.save()
#            request.user.message_set.create(message = 'Successfully saved group.')
            return HttpResponseRedirect(reverse('addressbook_index'))
    return render(request, 'addressbook/add_group.html',
            RequestContext(request, {'form':form}))


@login_required
def add_contact(request):
    if request.method == 'POST': # If the form has been submitted...
        contact_form = ContactForm(request.POST, user=request.user) # A form bound to the POST data
        # Create a formset from the submitted data
        email_formset = EmailFormSet(request.POST, prefix="email")
        phone_formset = PhoneFormSet(request.POST, prefix="phone")
        address_formset = AddressFormSet(request.POST, prefix="address")
        website_formset = WebsiteFormSet(request.POST, prefix="website")
        if (contact_form.is_valid() and email_formset.is_valid() and
                phone_formset.is_valid() and address_formset.is_valid() and
                website_formset.is_valid()):
            contact = contact_form.save()
            for form in email_formset.forms:
                email = form.save(commit=False)
                email.contact = contact
                email.save()
            for form in phone_formset.forms:
                phone = form.save(commit=False)
                phone.contact = contact
                phone.save()
            for form in address_formset.forms:
                address = form.save(commit=False)
                address.contact = contact
                address.save()
            for form in website_formset.forms:
                website = form.save(commit=False)
                website.contact = contact
                website.save()
#            request.user.message_set.create(message = 'Successfully saved contact.')
            return HttpResponseRedirect(reverse('addressbook_index')) # Redirect to a 'success' page
    else:
        groups = ContactGroup.objects.filter(user=request.user)
        if not groups:
            return HttpResponseRedirect(reverse('addressbook_add_group'))
        contact_form = ContactForm(user=request.user)
        email_formset = EmailFormSet(prefix="email")
        phone_formset = PhoneFormSet(prefix="phone")
        address_formset = AddressFormSet(prefix="address")
        website_formset = WebsiteFormSet(prefix="website")
    return render(request, 'addressbook/add_contact.html',
            RequestContext(request, {
                'phone_formset': phone_formset,
                'contact_form': contact_form,
                'email_formset': email_formset,
                'address_formset': address_formset,
                'website_formset': website_formset
            }))

@login_required
def edit_contact(request, pk):
    contact = Contact.objects.get(pk=pk)
    if contact.group.user != request.user:
        return HttpResponse(contact.group.user.username + request.user.username)
        #raise Http404
    if request.method == "POST":
        contact_form = ContactForm(request.POST, instance = contact, user = request.user)
        phone_formset = PhoneEditFormSet(request.POST, instance = contact, prefix="phone")
        address_formset = AddressEditFormSet(request.POST, instance = contact, prefix="address")
        email_formset = EmailEditFormSet(request.POST, instance = contact, prefix="email")
        website_formset = WebsiteEditFormSet(request.POST, instance = contact, prefix="website")
        if (contact_form.is_valid() and email_formset.is_valid() and
                address_formset.is_valid() and phone_formset.is_valid() and
                website_formset.is_valid()):
            contact_form.save()
            email_formset.save()
            address_formset.save()
            phone_formset.save()
            website_formset.save()
            return HttpResponseRedirect(reverse('addressbook_index'))
    else:
        contact_form = ContactForm(instance=contact, user=request.user)
        phone_formset = PhoneEditFormSet(instance = contact, prefix="phone")
        address_formset = AddressEditFormSet(instance = contact, prefix="address")
        email_formset = EmailEditFormSet(instance = contact, prefix="email")
        website_formset = WebsiteEditFormSet(instance = contact, prefix="website")
    return render(request, 'addressbook/edit_contact.html',
            RequestContext(request, {
                'email_formset':email_formset, 'phone_formset':phone_formset,
                'address_formset':address_formset, 'contact_form':contact_form,
                'website_formset':website_formset, 'contact':contact
            }))

# @login_required
# def index(request):
#     groups = ContactGroup.objects.filter(user=request.user)
#     contacts = Contact.objects.filter(group__user=request.user)
#     tup = [(group.name, Contact.objects.filter(group = group).order_by('last_name','first_name')) for group in groups]
#     #return render(request, 'addressbook/index.html', RequestContext(request, {'tup':tup, 'contacts':contacts}))
#     return render(request, 'addressbook/index.html', RequestContext(request, {'tup':tup, 'contacts':contacts}))

@login_required
def index(request):
    groups = ContactGroup.objects.filter(user=request.user)
    contacts = Contact.objects.filter(group__user=request.user)
    tup = [(group.name, Contact.objects.filter(group = group).order_by('last_name','first_name')) for group in groups]

    return render(request, 'addressbook/index.html', {
        'tup': tup,
        'contacts': contacts,
    })

    return render(request, 'addressbook/index.html', RequestContext(request, {'tup':tup, 'contacts':contacts}))



# #@login_required
# class IndexView(generic.ListView):
#     def get_queryset(self):
#         groups = ContactGroup.objects.filter(user=request.user)
#         contacts = Contact.objects.filter(group__user=request.user)
#         #return [(group.name, Contact.objects.filter(group=group).order_by('last_name', 'first_name')) for group in groups]
#         #tup = [(group.name, Contact.objects.filter(group = group).order_by('last_name','first_name')) for group in groups]
#         #return render(request, 'addressbook/index.html', RequestContext(request, {'tup':tup, 'contacts':contacts}))




def get_hash(str):
    str = str.lower().strip()
    md5 = hashlib.md5()
    md5.update(str)
    return md5.hexdigest()

@login_required
def single_contact(request, pk):
    contact = Contact.objects.get(pk = pk)
    if contact.group.user != request.user:
        raise Http404
    if request.method=="GET":
        emails = Email.objects.filter(contact = contact)
        hash = ''
        if emails:
            email = emails[0]
            hash = get_hash(email.email)
        # XXX is email required?
        addresses = Address.objects.filter(contact = contact)
        if addresses:
            address = addresses[0]
        phones = PhoneNumber.objects.filter(contact=contact)
        return render(request, 'addressbook/single_contact.html',
                RequestContext(request, {
                    'contact':contact, 'emails':emails, 'hash':hash,
                    'addresses':addresses, 'phones':phones,
                    'vcard_str': str(VCard(contact)),
                }))
    elif request.method=="POST":
        contact.delete()
        return HttpResponseRedirect(reverse('addressbook_index'))
    else:
        raise Http404

@login_required
def download_vcard(request, pk, vcard=VCard):
    """
    View function for returning single vcard
    """
    contact = Contact.objects.get(pk=pk)
    output = vcard(contact).output_string()
    filename = "contact_%s%s.vcf" % (contact.first_name, contact.last_name)
    response = HttpResponse(output, content_type="text/x-vCard")
    response['Content-Disposition'] = 'attachment; filename=%s' % filename
    return response

addressbook/templates/addressbook/add_contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrahead %}
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<!-- note that there's also blue.uni-form.css and dark.uni-form.css available if you want to try changing defaults up -->
<link rel="stylesheet" href="{{ MEDIA_URL }}css/addressbook.css" type="text/css" />
<script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
<script>
$(document).ready(function() {
  // Code adapted from http://djangosnippets.org/snippets/1389/
 
function updateElementIndex(el, prefix, ndx) {
    var id_regex = new RegExp('(' + prefix + '-\\d+-)');
    var replacement = prefix + '-' + ndx + '-';
    if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
 replacement));
    if (el.id) el.id = el.id.replace(id_regex, replacement);
    if (el.name) el.name = el.name.replace(id_regex, replacement);
  }
 
  function deleteForm(btn, prefix) {
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    //alert('formcount = ' + formCount);
    if (formCount > 1) {
      // Delete the item/form
      $(btn).parents('.' + prefix).remove();
 
      var forms = $('.' + prefix); // Get all the forms
        //alert(forms.length); 
      // Update the total number of forms (1 less than before)
      $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
 
      var i = 0;
      // Go through the forms and set their indices, names and IDs
      for (formCount = forms.length; i < formCount; i++) {
        $(forms.get(i)).children().children().each(function() {
          if ( $(this).attr('type') == 'text' )
            updateElementIndex(this, prefix, i);
        });
      }
 
    } // End if
    else {
        alert("You have to enter at least one "+prefix+"!");
    }
    return false;
  }
 
  function addForm(btn, prefix) {
    //alert(prefix);
    var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
    //alert(formCount); 
    // You can only submit a maximum of 10 todo items
    if (formCount < 3) {
      // Clone a form (without event handlers) from the first form
      var row = $("."+prefix+":first").clone(false).get(0);
      // Insert it after the last form
      $(row).append('<p class="left_wide"><a class="delete" href="#">remove</a></p>')
      $(row).removeAttr('id').hide().insertAfter("."+prefix+":last").addClass("dot-top").slideDown(300);
 
      // Remove the bits we don't want in the new row/form
      // e.g. error messages
      $(".errorlist", row).remove();
      $(row).children().removeClass("error");
 
      // Relabel or rename all the relevant bits
      $(row).children().children().each(function() {
        updateElementIndex(this, prefix, formCount);
        $(this).val("");
      });
 
      // Add an event handler for the delete item/form link
      $(row).find(".delete").click(function() {
        return deleteForm(this, prefix);
      });
 
      // Update the total form count
      $("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1); 
 
    } // End if
    else {
        var ending = ''; 
        if(prefix[prefix.length-1] == 's'){ 
            ending = 'es' 
        } 
        else {
            ending = 's'
        };
        alert("Sorry, you can only enter a maximum of 3 " + prefix + ending + ".");
    }
    return false;
  }
 
  // Register the click event handlers
  $(".add").click(function() {
    var prefix = $(this).parent().next().next().next().next().attr('class').split(" ")[0];//$(this).parent().prev().attr("class")
    return addForm(this, prefix);

  });
 
  $(".delete").click(function() {
    var prefix = $(this).parent().parent().attr("class");
    return deleteForm(this, prefix);
  });
 
});
</script>
{% endblock %}

{% block content %}
{% include "addressbook/links.html" %}

<div class="wrapper">
<form action="" method="post" class="uniForm">{% csrf_token %}
    <fieldset class="inlineLabels">
        <div class="dark">Add Contact Info</div>
        {{ contact_form|crispy }}
        <div class="dark">Email(s) <a class="add sm" href="#">Add another email</a></div>
        {{ email_formset.management_form }}
        {% for form in email_formset.forms %}
            <div class="{{email_formset.prefix}}">
              {{ form|crispy }}
            </div>
        {% endfor %}
     

        <div class="dark">Phone Number(s) <a class="add sm" href="#">Add another phone number</a></div>
        {{ phone_formset.management_form }}
        
        {% for form in phone_formset.forms %}
        <div class="{{phone_formset.prefix}}">
          {{ form|crispy }}
        </div>
        {% endfor %}
     

        <div class="dark">Address(es) <a class="add sm" href="#">Add another address</a></div>
        {{ address_formset.management_form }}
        
        {% for form in address_formset.forms %}
        <div class="{{address_formset.prefix}}">
          {{ form|crispy }}
        </div>
        {% endfor %}

        <div class="dark">Web site(s) <a class="add sm" href="#">Add another Web site</a></div>
        {{ website_formset.management_form }}

        {% for form in website_formset.forms %}
        <div class="{{website_formset.prefix}}">
          {{ form|crispy }}
        </div>
        {% endfor %}

        <div class="buttonHolder">
        <button class=primaryAction" type="submit">Add Contact</button>
        </div>
    </fieldset> 
 
</form>
</div>
{% endblock %}

addressbook/templates/addressbook/add_group.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block extrahead %}
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/addressbook.css" type="text/css" />
<!-- note that there's also blue.uni-form.css and dark.uni-form.css available if you want to try changing defaults up -->
<script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
{% endblock %}

{% block content %}
{% include "addressbook/links.html" %}

<div class="wrapper">
<form action="{% url "addressbook_add_group" %}" method="post" class="uniForm"> {% csrf_token %}
<fieldset class="inlineLabels">
<div class="dark">Add a contact group</div>
{{ form|crispy }}
<div class="buttonHolder">
<button class=primaryAction" type="submit">Add Group</button>
</div>
</fieldset>
</form>
</div>
{% endblock %}

addressbook/templates/addressbook/edit_contact.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block extrahead %}
    <link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/uni-form.css" type="text/css" />
    <link rel="stylesheet" href="{{ MEDIA_URL }}uni_form/default.uni-form.css" type="text/css" />
<link rel="stylesheet" href="{{ MEDIA_URL }}css/addressbook.css" type="text/css" />
    <script src="{{ MEDIA_URL }}uni_form/uni-form.jquery.js" type="text/javascript"></script>
    <script>
    $(document).ready(function() {
      // Code adapted from http://djangosnippets.org/snippets/1389/
    prefixes=['email','phone','address','website'];
    for (i in prefixes) {
        if ($('#id_'+prefixes[i]+'-INITIAL_FORMS').val() == "1") {
            var row = $("."+prefixes[i]+":first");
            $(row).children(":last").hide();
        }
    };
    function updateElementIndex(el, prefix, ndx) {
        var id_regex = new RegExp('(' + prefix + '-\\d+-)');
        var replacement = prefix + '-' + ndx + '-';
        if ($(el).attr("for")) $(el).attr("for", $(el).attr("for").replace(id_regex,
     replacement));
        if (el.id) el.id = el.id.replace(id_regex, replacement);
        if (el.name) el.name = el.name.replace(id_regex, replacement);
      }
     
      function deleteForm(btn, prefix) {
        var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        //alert('formcount = ' + formCount);
        if (formCount > 1) {
          // Delete the item/form
          $(btn).parents('.' + prefix).remove();
     
          var forms = $('.' + prefix); // Get all the forms
            //alert(forms.length); 
          // Update the total number of forms (1 less than before)
          $('#id_' + prefix + '-TOTAL_FORMS').val(forms.length);
     
          var i = 0;
          // Go through the forms and set their indices, names and IDs
          for (formCount = forms.length; i < formCount; i++) {
            $(forms.get(i)).children().children().each(function() {
              if ( $(this).attr('type') == 'text' )
                updateElementIndex(this, prefix, i);
            });
          }
     
        } // End if
        else {
            alert("You have to enter at least one "+prefix+"!");
        }
        return false;
      }
     
      function addForm(btn, prefix) {
        //alert(prefix);
        var formCount = parseInt($('#id_' + prefix + '-TOTAL_FORMS').val());
        //alert(formCount); 
        // You can only submit a maximum of 10 todo items
        if (formCount < 3) {
          // Clone a form (without event handlers) from the first form
          var row = $("."+prefix+":first").clone(false).get(0);
          // Insert it after the last form
            //$(row).children(':last').hide(); //hide delete field
            $(row).append('<p class="left_wide"><a class="delete" href="#">remove</a></p>')
           $(row).removeAttr('id').hide().insertAfter("."+prefix+":last").addClass("dot-top").slideDown(300);
          // Remove the bits we don't want in the new row/form
          // e.g. error messages
          $(".errorlist", row).remove();
          $(row).children().removeClass("error");
     
          // Relabel or rename all the relevant bits
          $(row).children().children().each(function() {
            updateElementIndex(this, prefix, formCount);
            $(this).val("");
          });
     
          // Add an event handler for the delete item/form link
          $(row).find(".delete").click(function() {
            return deleteForm(this, prefix);
          });
     
          // Update the total form count
          $("#id_" + prefix + "-TOTAL_FORMS").val(formCount + 1); 
     
        } // End if
        else {
            var ending = ''; 
            if(prefix[prefix.length-1] == 's'){ 
                ending = 'es' 
            } 
            else {
                ending = 's'
            };
            alert("Sorry, you can only enter a maximum of 3 " + prefix + ending + ".");
        }
        return false;
      }
     
      // Register the click event handlers
      $(".add").click(function() {
        var prefix = $(this).parent().next().next().next().next().attr('class').split(" ")[0];//$(this).parent().prev().attr("class")
        return addForm(this, prefix);

      });
     
      $(".delete").click(function() {
        var prefix = $(this).parent().parent().attr("class");
        return deleteForm(this, prefix);
      });
     
    });
</script>
{% endblock %}

{% block content %}

{% include "addressbook/links.html" %}

<div class="wrapper">
<h1>Editing {{contact.first_name}} {{contact.last_name}}'s Contact Info</h1>
<form action="" method="post" class="uniForm">{% csrf_token %}
    <fieldset class="inlineLabels">
        <div class="dark">Contact Information</div>
        {{ contact_form|crispy }}
        <div class="dark">Email(s) <a class="add sm" href="#">Add another email</a></div>
        {{ email_formset.management_form }}
        {% for form in email_formset.forms %}
        <div class="{{email_formset.prefix}}{% if not forloop.last %} dot{% endif %}">
          {{ form|crispy }}
        </div>
        {% endfor %}
        <div class="dark">Phone Number(s) <a class="add sm" href="#">Add another phone number</a></div>
        {{ phone_formset.management_form }}
        {% for form in phone_formset.forms %}
        <div class="{{phone_formset.prefix}}{% if not forloop.last %} dot{% endif %}">
          {{ form|crispy }}
        </div>
        {% endfor %}
        <div class="dark">Address(es) <a class="add sm" href="#">Add another address</a></div>
        {{ address_formset.management_form }}
        {% for form in address_formset.forms %}
        <div class="{{ address_formset.prefix }}{% if not forloop.last %} dot{% endif %}">
          {{ form|crispy }}
        </div>
        {% endfor %}

        <div class="dark">Web site(s) <a class="add sm" href="#">Add another Web site</a></div>
        {{ website_formset.management_form }}
        {% for form in website_formset.forms %}
        <div class="{{website_formset.prefix}}{% if not forloop.last %} dot{% endif %}">
          {{ form|crispy }}
        </div>
        {% endfor %}

        <div class="buttonHolder">
            <button class=primaryAction" type="submit">Submit Changes</button>
        </div>
    </fieldset> 
 
</form></div>
{% endblock %}

addressbook/templates/addressbook/hcard.html
<div id="hcard-{{ contact.first_name }}{% if contact.middle_name %}-{{ contact.middle_name }}{% endif %}-{{ contact.last_name }}" class="vcard">
<img src="http://www.gravatar.com/avatar/{{hash}}?s=50" alt="photo of {{contact.first_name}}" class="photo"/>
    {% if contact.url %}
    <a class="fn n url" href="{{contact.url}}">
    {% else %}
    <span class="fn n">
    {% endif %}
        <span class="given-name">{{ contact.first_name }}</span>
        <span class="additional-name">{{ contact.middle_name }}</span>
        <span class="family-name">{{ contact.last_name }}</span>
    {% if contact.url %}
    </a>
    {% else %}
    </span>
    {% endif %}
{% if contact.title %}<span class="title">{{ contact.title}}</span>{% endif %}
{% if contact.organization %}<div class="org">{{ contact.organization }}</div>{% endif %}
    <br clear="all" />
    {% for email in emails %}
    <span class="type">{{email.type|lower}}</span>: <a class="email" href="mailto:{{ email.email }}">{{ email.email }}</a><br />
    {% endfor %}
    {% for address in addresses %}
    <div class="adr"><span class="type">{{address.type|lower}}</span>: 
        <div class="street-address">{{address.street}}</div>
        <br />        
        <span class="locality">{{ address.city }}</span>,
        <span class="region">{{ address.state }}</span>
        <span class="postal-code">{{ address.zip }}</span>
        <span class="country-name">United States</span>
    </div>
    
    {% endfor %}
    {% for phone in phones %}
    <div class="tel"><span class="type">{{ phone.type|lower }}</span>: <span class="value">{{ phone.phone }}</span></div>
    {% endfor %}
</div>

addressbook/templates/addressbook/links.html
<div class="wrapper">
<p>
{% if user.is_authenticated %}
        <a href="{% url 'addressbook:addressbook_index' %}">My Address Book</a>
        <a href="{% url 'addressbook:addressbook_add_group' %}">Add Group</a>
        <a href="{% url 'addressbook:addressbook_add_contact' %}">Add Contact</a>
{% else %}
You are not logged in
{% endif %}
</p>
</div>